### ISSUE TITLE
problem of loading pretrained model

### ISSUE THREAD

**Issue by nima766** [MKFMIKU/Instance-Shadow-Diffusion#1]
When I load the model, I get this error, 
"**RuntimeError: Error(s) in loading state_dict for DensePosteriorConditionalUNet:
	size mismatch for out.2.weight: copying a param with shape torch.Size([6, 192, 3, 3]) from checkpoint, the shape in current model is torch.Size([3, 192, 3, 3]).
	size mismatch for out.2.bias: copying a param with shape torch.Size([6]) from checkpoint, the shape in current model is torch.Size([3]).**"

even if I change the settings,
"
 model = DensePosteriorConditionalUNet(
        in_channels=3 + 3 + 1,
        out_channels=6,
        model_channels=192,
        num_res_blocks=2,
        attention_resolutions=[8, 16, 32],
        num_heads=4,
        num_head_channels=64,
        num_heads_upsample=-1,
        channel_mult=[1, 1, 2, 2, 2, 4],
        dropout=0.0,
        use_scale_shift_norm=True,
        resblock_updown=True,
        use_new_attention_order=True,
    )
"
 I get this problem:
 "  **File "/tmp/p2w/guided_diffusion/gaussian_diffusion.py", line 340, in _predict_xstart_from_eps
    assert x_t.shape == eps.shape**"
    
x_t :  torch.Size([1, 3, 256, 256])
eps : torch.Size([1, 6, 256, 256])

**Comment by XinghuaHuang02** [comment]
I get the same bug. Did you find out how to solve it?

**Comment by MKFMIKU** [comment]
thank you for your attention to this problem. I will get back to you quickly for this issue.

Best,
Kangfu Mei

**Comment by MKFMIKU** [comment]
@XinghuaHuang02 @nima766 Thank you for your attention to our work!

The issue comes from the inconsistent setting between the training and testing. I have fixed them in https://github.com/MKFMIKU/Instance-Shadow-Diffusion/commit/628ae79c97c9efd713df51f91a89586b3d81ee79

**Comment by XinghuaHuang02** [comment]
Thank you very much, it can run right now😊

**Comment by nima766** [comment]
Thank you very much, it works properly.
