### ISSUE TITLE
Which dataset is the pre-trained model on?

### ISSUE THREAD

**Issue by Aerobex** [MKFMIKU/Instance-Shadow-Diffusion#2]
Tried to test on the AISTD dataset, though the results were quite different from the paper results?

**Comment by MKFMIKU** [comment]
The released model is pre-trained on AISTD dataset. Could you please provide more details about the results difference?

**Comment by Aerobex** [comment]
> The released model is pre-trained on AISTD dataset. Could you please provide more details about the results difference?

I have contacted your email to send the results of the test，hoping for your answe。
