### ISSUE TITLE
how to remove shadow in custom pic 

### ISSUE THREAD

**Issue by shidalao** [MKFMIKU/Instance-Shadow-Diffusion#3]
rt, just download this project and dataset, but can't find any solution with custom pic.

such as this pic.
![custom](https://github.com/MKFMIKU/Instance-Shadow-Diffusion/assets/127720822/94df991a-3165-4884-90c6-e53cf7675521)

**Comment by MKFMIKU** [comment]
Hi @shidalao , thanks for attention in our project. You can try to use our web-dem https://huggingface.co/spaces/MKFMIKU/Instance-Shadow-Removal. Or check the inference code behind the web-demo and run it offline.

**Comment by shidalao** [comment]
So where is the inference code ?

**Comment by MKFMIKU** [comment]
@shidalao You can check the code here https://huggingface.co/spaces/MKFMIKU/Instance-Shadow-Removal/blob/main/diffusion.py.

**Comment by smart4654154** [comment]
> @shidalao You can check the code here https://huggingface.co/spaces/MKFMIKU/Instance-Shadow-Removal/blob/main/diffusion.py.

hi,huggging face demo is bad,could you fix it.thank you
